module.exports = [
{"name":"English","script":"English","code":"en"},
{"name":"German","script":"Latn","code":"de"},
{"name":"French","script":"Latn","code":"fr"},
{"name":"Dutch","script":"Latn","code":"nl"},
{"name":"Italian","script":"Latn","code":"it"},
{"name":"Spanish","script":"Latn","code":"es"},
{"name":"Russian","script":"Cyrl","code":"ru"},
{"name":"Swedish","script":"Latn","code":"sv"},
{"name":"Polish","script":"Latn","code":"pl"},
{"name":"Japanese","script":"Jpan","code":"ja"},
{"name":"Portuguese","script":"English","code":"pt"},
{"name":"Arabic","script":"Arab","code":"ar"},
{"name":"Chinese","script":"Hans/Hant","code":"zh"},
{"name":"Ukrainian","script":"Cyrl","code":"uk"},
{"name":"Catalan","script":"Latn","code":"ca"},
{"name":"Norwegian (Bokmål)","script":"Latn","code":"no"},
{"name":"Finnish","script":"Latn","code":"fi"},
{"name":"Czech","script":"Latn","code":"cs"},
{"name":"Hungarian","script":"Latn","code":"hu"},
{"name":"Turkish","script":"Latn","code":"tr"},
{"name":"Romanian","script":"Latn","code":"ro"},
{"name":"Swahili","script":"English","code":"sw"},
{"name":"Korean","script":"Hang","code":"ko"},
{"name":"Kazakh","script":"Cyrl / Latin / Arab","code":"kk"},
{"name":"Vietnamese","script":"Latn","code":"vi"},
{"name":"Danish","script":"Latn","code":"da"},
{"name":"Esperanto","script":"Latn","code":"eo"},
{"name":"Serbian","script":"Cyrl/Latn","code":"sr"},
{"name":"Indonesian","script":"Latn","code":"id"},
{"name":"Lithuanian","script":"Latn","code":"lt"},
{"name":"Volapük","script":"Latn","code":"vo"},
{"name":"Slovak","script":"Latn","code":"sk"},
{"name":"Hebrew","script":"Hebr","code":"he"},
{"name":"Persian","script":"Perso","code":"fa"},
{"name":"Bulgarian","script":"Cyrl","code":"bg"},
{"name":"Slovene","script":"Latn","code":"sl"},
{"name":"Basque","script":"Latn","code":"eu"},
{"name":"Waray-Waray","script":"Latn","code":"war"},
{"name":"Lombard","script":"Latn","code":"lmo"},
{"name":"Estonian","script":"Latn","code":"et"},
{"name":"Croatian","script":"Latn","code":"hr"},
{"name":"Newar / Nepal Bhasa","script":"Deva","code":"new"},
{"name":"Telugu","script":"Telu","code":"te"},
{"name":"Norwegian (Nynorsk)","script":"Latn","code":"nn"},
{"name":"Thai","script":"Thai","code":"th"},
{"name":"Galician","script":"Latn","code":"gl"},
{"name":"Greek","script":"Grek","code":"el"},
{"name":"Cebuano","script":"Latn","code":"ceb"},
{"name":"Simple English","script":"Latn","code":"simple"},
{"name":"Malay","script":"Latn","code":"ms"},
{"name":"Haitian","script":"Latn","code":"ht"},
{"name":"Bosnian","script":"Latn","code":"bs"},
{"name":"Bishnupriya Manipuri","script":"Beng","code":"bpy"},
{"name":"Luxembourgish","script":"Latn","code":"lb"},
{"name":"Georgian","script":"Geor","code":"ka"},
{"name":"Icelandic","script":"Latn","code":"is"},
{"name":"Albanian","script":"Latn","code":"sq"},
{"name":"Latin","script":"Latn","code":"la"},
{"name":"Breton","script":"Latn","code":"br"},
{"name":"Hindi","script":"Deva","code":"hi"},
{"name":"Azerbaijani","script":"Latn/Arab","code":"az"},
{"name":"Bengali","script":"Beng","code":"bn"},
{"name":"Macedonian","script":"Cyrl","code":"mk"},
{"name":"Marathi","script":"Deva","code":"mr"},
{"name":"Serbo-Croatian","script":"Latn/Cyrl","code":"sh"},
{"name":"Tagalog","script":"Latn","code":"tl"},
{"name":"Welsh","script":"Latn","code":"cy"},
{"name":"Ido","script":"Latn","code":"io"},
{"name":"Piedmontese","script":"Latn","code":"pms"},
{"name":"Latvian","script":"Latn","code":"lv"},
{"name":"Tamil","script":"Taml","code":"ta"},
{"name":"Sundanese","script":"Latn","code":"su"},
{"name":"Occitan","script":"Latn","code":"oc"},
{"name":"Javanese","script":"Latn","code":"jv"},
{"name":"Neapolitan","script":"Latn","code":"nap"},
{"name":"Low Saxon","script":"Latn","code":"nds"},
{"name":"Sicilian","script":"Latn","code":"scn"},
{"name":"Belarusian","script":"Cyrl","code":"be"},
{"name":"Asturian","script":"Latn","code":"ast"},
{"name":"Kurdish","script":"Latn/Arab","code":"ku"},
{"name":"Walloon","script":"Latn","code":"wa"},
{"name":"Afrikaans","script":"Latn","code":"af"},
{"name":"Belarusian (Taraškievica)","script":"Cyrl","code":"be-x-old"},
{"name":"Aragonese","script":"Latn","code":"an"},
{"name":"Ripuarian","script":"Latn","code":"ksh"},
{"name":"Silesian","script":"Latn","code":"szl"},
{"name":"West Frisian","script":"Latn","code":"fy"},
{"name":"North Frisian","script":"Latn","code":"frr"},
{"name":"Cantonese","script":"Hant","code":"yue"},
{"name":"Urdu","script":"Arab","code":"ur"},
{"name":"Interlingua","script":"Latn/Arab","code":"ia"},
{"name":"Irish","script":"Latn","code":"ga"},
{"name":"Yiddish","script":"Hebr","code":"yi"},
{"name":"Alemannic","script":"Latn","code":"als"},
{"name":"Armenian","script":"Armn","code":"hy"},
{"name":"Amharic","script":"Geez","code":"am"},
{"name":"Aromanian","script":"Latn","code":"roa-rup"},
{"name":"Banyumasan","script":"Latn","code":"map-bms"},
{"name":"Bihari","script":"Deva","code":"bh"},
{"name":"Corsican","script":"Latn","code":"co"},
{"name":"Chuvash","script":"Latn","code":"cv"},
{"name":"Divehi","script":"Thaa","code":"dv"},
{"name":"Dutch Low Saxon","script":"Latn","code":"nds-nl"},
{"name":"Faroese","script":"Latn","code":"fo"},
{"name":"Friulian","script":"Latn","code":"fur"},
{"name":"Gilaki","script":"Perso","code":"glk"},
{"name":"Gujarati","script":"Gujr","code":"gu"},
{"name":"Ilokano","script":"Latn","code":"ilo"},
{"name":"Kannada","script":"Knda","code":"kn"},
{"name":"Kapampangan","script":"Latn","code":"pam"},
{"name":"Kashubian","script":"Latn","code":"csb"},
{"name":"Khmer","script":"Khmr","code":"km"},
{"name":"Ligurian","script":"Latn","code":"lij"},
{"name":"Limburgish","script":"Latn","code":"li"},
{"name":"Malayalam","script":"Mlym","code":"ml"},
{"name":"Manx","script":"Latn","code":"gv"},
{"name":"Māori","script":"Latn","code":"mi"},
{"name":"Maltese","script":"Latn","code":"mt"},
{"name":"Nāhuatl","script":"Latn","code":"nah"},
{"name":"Nepali","script":"Deva","code":"ne"},
{"name":"Norman","script":"Latn","code":"nrm"},
{"name":"Northern Sami","script":"Latn","code":"se"},
{"name":"Novial","script":"Latn","code":"nov"},
{"name":"Quechua","script":"Latn","code":"qu"},
{"name":"Ossetian","script":"Cyrl","code":"os"},
{"name":"Pali","script":"Deva","code":"pi"},
{"name":"Pangasinan","script":"Latn","code":"pag"},
{"name":"Pashto","script":"Arab","code":"ps"},
{"name":"Pennsylvania German","script":"Latn","code":"pdc"},
{"name":"Romansh","script":"Latn","code":"rm"},
{"name":"Samogitian","script":"Latn","code":"bat-smg"},
{"name":"Sanskrit","script":"Deva","code":"sa"},
{"name":"Scottish Gaelic","script":"Latn","code":"gd"},
{"name":"Scots","script":"Latn","code":"sco"},
{"name":"Sardinian","script":"Latn","code":"sc"},
{"name":"Sinhalese","script":"Sinh","code":"si"},
{"name":"Tajik","script":"Cyrl","code":"tg"},
{"name":"Tarantino","script":"Latn","code":"roa-tara"},
{"name":"Tatar","script":"Cyrl/Latn","code":"tt"},
{"name":"Tongan","script":"Latn","code":"to"},
{"name":"Turkmen","script":"Latn","code":"tk"},
{"name":"Upper Sorbian","script":"Latn","code":"hsb"},
{"name":"Uzbek","script":"Latn/Cyrl","code":"uz"},
{"name":"Venetian","script":"Latn","code":"vec"},
{"name":"Võro","script":"Latn","code":"fiu-vro"},
{"name":"Wu","script":"Hans","code":"wuu"},
{"name":"West Flemish","script":"Latn","code":"vls"},
{"name":"Yoruba","script":"Latn","code":"yo"},
{"name":"Zazaki","script":"Latn","code":"diq"},
{"name":"Min Nan","script":"Latn","code":"zh-min-nan"},
{"name":"Classical Chinese","script":"Hant","code":"zh-classical"},
{"name":"Franco-Provençal/Arpitan","script":"Latn","code":"frp"},
{"name":"Ladino","script":"Latn","code":"lad"},
{"name":"Bavarian","script":"Latn","code":"bar"},
{"name":"Central_Bicolano","script":"Latn","code":"bcl"},
{"name":"Cornish","script":"Latn","code":"kw"},
{"name":"Mongolian","script":"Cyrl","code":"mn"},
{"name":"Hawaiian","script":"Latn","code":"haw"},
{"name":"Anglo-Saxon","script":"Latn","code":"ang"},
{"name":"Lingala","script":"Latn","code":"ln"},
{"name":"Interlingue","script":"Latn","code":"ie"},
{"name":"Wolof","script":"Latn","code":"wo"},
{"name":"Tok Pisin","script":"Latn","code":"tpi"},
{"name":"Tahitian","script":"Latn","code":"ty"},
{"name":"Crimean Tatar","script":"Latn","code":"crh"},
{"name":"Lojban","script":"Latn","code":"jbo"},
{"name":"Aymara","script":"Latn","code":"ay"},
{"name":"Zealandic","script":"Latn","code":"zea"},
{"name":"Emilian-Romagnol","script":"Latn","code":"eml"},
{"name":"Kyrgyz","script":"Cyrl","code":"ky"},
{"name":"Igbo","script":"Latn","code":"ig"},
{"name":"Oriya","script":"Orya","code":"or"},
{"name":"Malagasy","script":"Latn","code":"mg"},
{"name":"Zamboanga Chavacano","script":"Latn","code":"cbk-zam"},
{"name":"Kongo","script":"Latn","code":"kg"},
{"name":"Syriac","script":"Syrc","code":"arc"},
{"name":"Vlax Romani","script":"Latn/Deva","code":"rmy"},
{"name":"Guarani","script":"Latn","code":"gn"},
{"name":"Moldovan","script":"Cyrl","code":"mo (closed)"},
{"name":"Somali","script":"Latn","code":"so"},
{"name":"Kabyle","script":"Latn","code":"kab"},
{"name":"Kashmiri","script":"Arab/Deva","code":"ks"},
{"name":"Saterland Frisian","script":"Latn","code":"stq"},
{"name":"Chechen","script":"Cyrl","code":"ce"},
{"name":"Udmurt","script":"Cyrl","code":"udm"},
{"name":"Mazandarani","script":"Perso","code":"mzn"},
{"name":"Papiamentu","script":"Latn","code":"pap"},
{"name":"Old Church Slavonic","script":"Cyrs","code":"cu"},
{"name":"Sakha","script":"Cyrl","code":"sah"},
{"name":"Tetum","script":"Latn","code":"tet"},
{"name":"Sindhi","script":"Arab","code":"sd"},
{"name":"Lao","script":"Laoo","code":"lo"},
{"name":"Bashkir","script":"Cyrl","code":"ba"},
{"name":"Punjabi","script":"Shahmukhi","code":"pnb"},
{"name":"Inuktitut","script":"Cans/Latn","code":"iu"},
{"name":"Nauruan","script":"Latn","code":"na"},
{"name":"Gothic","script":"Goth","code":"got"},
{"name":"Tibetan","script":"Tibt","code":"bo"},
{"name":"Lower Sorbian","script":"Latn","code":"dsb"},
{"name":"Cherokee","script":"Cher","code":"chr"},
{"name":"Min Dong","script":"Latn","code":"cdo"},
{"name":"Hakka","script":"Latn","code":"hak"},
{"name":"Oromo","script":"Latn","code":"om"},
{"name":"Burmese","script":"Mymr","code":"my"},
{"name":"Samoan","script":"Latn","code":"sm"},
{"name":"Ewe","script":"Latn","code":"ee"},
{"name":"Picard","script":"Latn","code":"pcd"},
{"name":"Uyghur","script":"Latn/Arab","code":"ug"},
{"name":"Assamese","script":"Beng","code":"as"},
{"name":"Tigrinya","script":"Ethi","code":"ti"},
{"name":"Avar","script":"Cyrl","code":"av"},
{"name":"Bambara","script":"Latn","code":"bm"},
{"name":"Zulu","script":"Latn","code":"zu"},
{"name":"Pontic","script":"Grek","code":"pnt"},
{"name":"Navajo","script":"Latn","code":"nv"},
{"name":"Cree","script":"Cans/Latn","code":"cr"},
{"name":"Norfolk","script":"Latn","code":"pih"},
{"name":"Swati","script":"Latn","code":"ss"},
{"name":"Venda","script":"Latn","code":"ve"},
{"name":"Bislama","script":"Latn","code":"bi"},
{"name":"Kinyarwanda","script":"Latn","code":"rw"},
{"name":"Chamorro","script":"Latn","code":"ch"},
{"name":"Egyptian Arabic","script":"Arab/Latn","code":"arz"},
{"name":"Xhosa","script":"Latn","code":"xh"},
{"name":"Greenlandic","script":"Latn","code":"kl"},
{"name":"Inupiak","script":"Latn","code":"ik"},
{"name":"Buginese","script":"Bugi","code":"bug"},
{"name":"Dzongkha","script":"Tibt","code":"dz"},
{"name":"Tsonga","script":"Latn","code":"ts"},
{"name":"Tswana","script":"Latn","code":"tn"},
{"name":"Komi","script":"Cyrl","code":"kv"},
{"name":"Tumbuka","script":"Latn","code":"tum"},
{"name":"Kalmyk","script":"Cyrl","code":"xal"},
{"name":"Sesotho","script":"Latn","code":"st"},
{"name":"Twi","script":"Latn","code":"tw"},
{"name":"Buryat (Russia)","script":"Cyrl","code":"bxr"},
{"name":"Akan","script":"Latn","code":"ak"},
{"name":"Abkhazian","script":"Cyrl","code":"ab"},
{"name":"Chichewa","script":"Latn","code":"ny"},
{"name":"Fijian","script":"Latn","code":"fj"},
{"name":"Lak","script":"Cyrl","code":"lbe"},
{"name":"Kikuyu","script":"Latn","code":"ki"},
{"name":"Zhuang","script":"Latn","code":"za"},
{"name":"Fula","script":"Latn","code":"ff"},
{"name":"Luganda","script":"Latn","code":"lg"},
{"name":"Shona","script":"Latn","code":"sn"},
{"name":"Hausa","script":"Latn","code":"ha"},
{"name":"Sango","script":"Latn","code":"sg"},
{"name":"Sichuan Yi","script":"Yiii","code":"ii"},
{"name":"Choctaw","script":"Latn","code":"cho"},
{"name":"Kirundi","script":"Latn","code":"rn"},
{"name":"Marshallese","script":"Latn","code":"mh"},
{"name":"Cheyenne","script":"Latn","code":"chy"},
{"name":"Ndonga","script":"Latn","code":"ng"},
{"name":"Kuanyama","script":"Latn","code":"kj"},
{"name":"Hiri Motu","script":"Latn","code":"ho"},
{"name":"Muscogee","script":"Latn","code":"mus"},
{"name":"Kanuri","script":"Latn","code":"kr"},
{"name":"Herero","script":"Latn","code":"hz"},
{"name":"Moloko","script":"Latn","code":"mwl"},
{"name":"Punjabi","script":"Guru","code":"pa"},
{"name":"Mingrelian","script":"Geor","code":"xmf"},
{"name":"Lezgian","script":"Cyrl","code":"lez"},
{"name":"Champenoisian","script":"Latn","code":"chm"}
]